services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}
  web:
    build: .
    restart: always
    command: ./start.sh
    links:
      - "db:db"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy