# Generated by Django 5.1.6 on 2025-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('densha_api_app', '0002_delete_area_rename_route_id_route_route_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
